"""initial_schema

Revision ID: 06b5cc5dbfa6
Revises: c4def0aec005
Create Date: 2026-04-05 23:39:24.683928
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as postgresql


# revision identifiers, used by Alembic.
revision: str = '06b5cc5dbfa6'
down_revision: str | None = 'c4def0aec005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('requested_by_type', sa.String(length=20), nullable=False),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_created_at'), 'approval_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_index(op.f('ix_approval_requests_tenant_id'), 'approval_requests', ['tenant_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('before_state', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_business_number', sa.String(length=8), nullable=False),
    sa.Column('billing_address', sa.Text(), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=False),
    sa.Column('contact_email', sa.String(length=254), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_index('uq_customers_tenant_business_number', 'customers', ['tenant_id', 'normalized_business_number'], unique=True)
    op.create_table('invoice_number_ranges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('prefix', sa.String(length=2), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_number_ranges'))
    )
    op.create_index(op.f('ix_invoice_number_ranges_tenant_id'), 'invoice_number_ranges', ['tenant_id'], unique=False)
    op.create_index('uq_invoice_number_ranges_tenant_prefix_start_end', 'invoice_number_ranges', ['tenant_id', 'prefix', 'start_number', 'end_number'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=10), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_type', sa.String(length=10), nullable=False),
    sa.Column('buyer_identifier_snapshot', sa.String(length=10), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.Column('replaces_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('replaced_by_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_invoices_customer_id_customers'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_index('uq_invoices_tenant_invoice_number', 'invoices', ['tenant_id', 'invoice_number'], unique=True)
    op.create_table('legacy_import_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.String(length=120), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('target_schema', sa.String(length=63), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('requested_tables', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legacy_import_runs')),
    sa.UniqueConstraint('tenant_id', 'batch_id', 'attempt_number', name='uq_legacy_import_runs_tenant_batch_attempt')
    )
    op.create_index(op.f('ix_legacy_import_runs_tenant_id'), 'legacy_import_runs', ['tenant_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_terms_code', sa.String(length=20), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_orders_customer_id_customers', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index('ix_orders_tenant_created', 'orders', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_index('ix_orders_tenant_status', 'orders', ['tenant_id', 'status'], unique=False)
    op.create_index('uq_orders_tenant_order_number', 'orders', ['tenant_id', 'order_number'], unique=True)
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_index(op.f('ix_product_tenant_id'), 'product', ['tenant_id'], unique=False)
    op.create_index('uq_product_tenant_code', 'product', ['tenant_id', 'code'], unique=True)
    op.create_table('supplier',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('default_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier'))
    )
    op.create_index(op.f('ix_supplier_tenant_id'), 'supplier', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('warehouse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse'))
    )
    op.create_index(op.f('ix_warehouse_tenant_id'), 'warehouse', ['tenant_id'], unique=False)
    op.create_index('uq_warehouse_tenant_code', 'warehouse', ['tenant_id', 'code'], unique=True)
    op.create_table('egui_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('fia_reference', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='fk_egui_submissions_invoice_id_invoices'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_egui_submissions'))
    )
    op.create_index(op.f('ix_egui_submissions_tenant_id'), 'egui_submissions', ['tenant_id'], unique=False)
    op.create_index('uq_egui_submissions_tenant_invoice', 'egui_submissions', ['tenant_id', 'invoice_id'], unique=True)
    op.create_table('inventory_stock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_inventory_stock_product_id_product')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_inventory_stock_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_stock'))
    )
    op.create_index(op.f('ix_inventory_stock_tenant_id'), 'inventory_stock', ['tenant_id'], unique=False)
    op.create_index('ix_inventory_stock_warehouse_product', 'inventory_stock', ['warehouse_id', 'product_id'], unique=False)
    op.create_index('uq_inventory_stock_tenant_product_warehouse', 'inventory_stock', ['tenant_id', 'product_id', 'warehouse_id'], unique=True)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('product_code_snapshot', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('tax_type', sa.Integer(), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('zero_tax_rate_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='fk_invoice_lines_invoice_id_invoices'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_lines'))
    )
    op.create_index(op.f('ix_invoice_lines_tenant_id'), 'invoice_lines', ['tenant_id'], unique=False)
    op.create_index('uq_invoice_lines_invoice_id_line_number', 'invoice_lines', ['invoice_id', 'line_number'], unique=True)
    op.create_table('legacy_import_table_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=120), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('expected_row_count', sa.Integer(), nullable=True),
    sa.Column('loaded_row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['legacy_import_runs.id'], name=op.f('fk_legacy_import_table_runs_run_id_legacy_import_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legacy_import_table_runs')),
    sa.UniqueConstraint('run_id', 'table_name', name='uq_legacy_import_table_runs_run_table')
    )
    op.create_index(op.f('ix_legacy_import_table_runs_run_id'), 'legacy_import_table_runs', ['run_id'], unique=False)
    op.create_table('line_customer_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('line_user_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_line_customer_mappings_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_line_customer_mappings')),
    sa.UniqueConstraint('tenant_id', 'line_user_id', name='uq_line_mapping_tenant_user')
    )
    op.create_index(op.f('ix_line_customer_mappings_tenant_id'), 'line_customer_mappings', ['tenant_id'], unique=False)
    op.create_table('order_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('tax_policy_code', sa.String(length=20), nullable=False),
    sa.Column('tax_type', sa.Integer(), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('available_stock_snapshot', sa.Integer(), nullable=True),
    sa.Column('backorder_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_order_lines_order_id_orders', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='fk_order_lines_product_id_product', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_lines'))
    )
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('payment_ref', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suggested_invoice_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_payments_customer_id_customers', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='fk_payments_invoice_id_invoices', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['suggested_invoice_id'], ['invoices.id'], name='fk_payments_suggested_invoice_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index('ix_payments_match_status', 'payments', ['tenant_id', 'match_status'], unique=False)
    op.create_index('ix_payments_tenant_customer', 'payments', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_payments_tenant_date', 'payments', ['tenant_id', 'payment_date'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_index('ix_payments_tenant_invoice', 'payments', ['tenant_id', 'invoice_id'], unique=False)
    op.create_index('ix_payments_tenant_invoice_match', 'payments', ['tenant_id', 'invoice_id', 'match_status'], unique=False)
    op.create_index('uq_payments_tenant_payment_ref', 'payments', ['tenant_id', 'payment_ref'], unique=True)
    op.create_table('reorder_alert',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'acknowledged', 'resolved', name='alert_status_enum', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_reorder_alert_product_id_product')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_reorder_alert_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reorder_alert'))
    )
    op.create_index(op.f('ix_reorder_alert_tenant_id'), 'reorder_alert', ['tenant_id'], unique=False)
    op.create_index('uq_reorder_alert_tenant_product_warehouse', 'reorder_alert', ['tenant_id', 'product_id', 'warehouse_id'], unique=True)
    op.create_table('stock_adjustment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('reason_code', sa.Enum('RECEIVED', 'DAMAGED', 'RETURNED', 'CORRECTION', 'OTHER', 'SUPPLIER_DELIVERY', 'TRANSFER_OUT', 'TRANSFER_IN', name='reason_code_enum', create_constraint=True), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transfer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_stock_adjustment_product_id_product')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_stock_adjustment_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_adjustment'))
    )
    op.create_index(op.f('ix_stock_adjustment_tenant_id'), 'stock_adjustment', ['tenant_id'], unique=False)
    op.create_table('stock_transfer_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('from_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('to_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouse.id'], name=op.f('fk_stock_transfer_history_from_warehouse_id_warehouse')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_stock_transfer_history_product_id_product')),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouse.id'], name=op.f('fk_stock_transfer_history_to_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_transfer_history'))
    )
    op.create_index(op.f('ix_stock_transfer_history_tenant_id'), 'stock_transfer_history', ['tenant_id'], unique=False)
    op.create_table('supplier_order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'SHIPPED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', name='supplier_order_status_enum', create_constraint=True), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_arrival_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplier_order_supplier_id_supplier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_order'))
    )
    op.create_index('ix_supplier_order_status_date', 'supplier_order', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_supplier_order_tenant_id'), 'supplier_order', ['tenant_id'], unique=False)
    op.create_table('supplier_order_line',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['supplier_order.id'], name=op.f('fk_supplier_order_line_order_id_supplier_order')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_supplier_order_line_product_id_product')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_supplier_order_line_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_order_line'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_order_line')
    op.drop_index(op.f('ix_supplier_order_tenant_id'), table_name='supplier_order')
    op.drop_index('ix_supplier_order_status_date', table_name='supplier_order')
    op.drop_table('supplier_order')
    op.drop_index(op.f('ix_stock_transfer_history_tenant_id'), table_name='stock_transfer_history')
    op.drop_table('stock_transfer_history')
    op.drop_index(op.f('ix_stock_adjustment_tenant_id'), table_name='stock_adjustment')
    op.drop_table('stock_adjustment')
    op.drop_index('uq_reorder_alert_tenant_product_warehouse', table_name='reorder_alert')
    op.drop_index(op.f('ix_reorder_alert_tenant_id'), table_name='reorder_alert')
    op.drop_table('reorder_alert')
    op.drop_index('uq_payments_tenant_payment_ref', table_name='payments')
    op.drop_index('ix_payments_tenant_invoice_match', table_name='payments')
    op.drop_index('ix_payments_tenant_invoice', table_name='payments')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index('ix_payments_tenant_date', table_name='payments')
    op.drop_index('ix_payments_tenant_customer', table_name='payments')
    op.drop_index('ix_payments_match_status', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_lines_order_id'), table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index(op.f('ix_line_customer_mappings_tenant_id'), table_name='line_customer_mappings')
    op.drop_table('line_customer_mappings')
    op.drop_index(op.f('ix_legacy_import_table_runs_run_id'), table_name='legacy_import_table_runs')
    op.drop_table('legacy_import_table_runs')
    op.drop_index('uq_invoice_lines_invoice_id_line_number', table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_tenant_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index('uq_inventory_stock_tenant_product_warehouse', table_name='inventory_stock')
    op.drop_index('ix_inventory_stock_warehouse_product', table_name='inventory_stock')
    op.drop_index(op.f('ix_inventory_stock_tenant_id'), table_name='inventory_stock')
    op.drop_table('inventory_stock')
    op.drop_index('uq_egui_submissions_tenant_invoice', table_name='egui_submissions')
    op.drop_index(op.f('ix_egui_submissions_tenant_id'), table_name='egui_submissions')
    op.drop_table('egui_submissions')
    op.drop_index('uq_warehouse_tenant_code', table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_tenant_id'), table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_supplier_tenant_id'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index('uq_product_tenant_code', table_name='product')
    op.drop_index(op.f('ix_product_tenant_id'), table_name='product')
    op.drop_table('product')
    op.drop_index('uq_orders_tenant_order_number', table_name='orders')
    op.drop_index('ix_orders_tenant_status', table_name='orders')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index('ix_orders_tenant_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_legacy_import_runs_tenant_id'), table_name='legacy_import_runs')
    op.drop_table('legacy_import_runs')
    op.drop_index('uq_invoices_tenant_invoice_number', table_name='invoices')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('uq_invoice_number_ranges_tenant_prefix_start_end', table_name='invoice_number_ranges')
    op.drop_index(op.f('ix_invoice_number_ranges_tenant_id'), table_name='invoice_number_ranges')
    op.drop_table('invoice_number_ranges')
    op.drop_index('uq_customers_tenant_business_number', table_name='customers')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_approval_requests_tenant_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_created_at'), table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###