"""add_app_settings

Revision ID: 5b3a41527547
Revises: 06b5cc5dbfa6
Create Date: 2026-04-05 23:41:49.464782
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3a41527547'
down_revision: str | None = '06b5cc5dbfa6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_app_settings_updated_by_users'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_invoice_id_invoices', 'orders', type_='foreignkey')
    op.drop_constraint('fk_invoices_order_id_orders', 'invoices', type_='foreignkey')
    op.drop_table('app_settings')
    # ### end Alembic commands ###