/**
 * i18n Type Generator
 * 
 * This file is AUTO-GENERATED by scripts/generate-i18n-types.ts
 * DO NOT EDIT MANUALLY - run `pnpm generate:i18n-types` to regenerate
 * 
 * Generates TypeScript types from locale JSON files for type-safe translations.
 */

import { I18N_NAMESPACES } from './i18n-namespaces';

// =============================================================================
// ENGLISH TRANSLATIONS - Source of Truth for Keys
// =============================================================================

export const en = {
  common: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    create: "Create",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Info",
    confirm: "Confirm",
    close: "Close",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    reset: "Reset",
    apply: "Apply",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    required: "Required",
    optional: "Optional",
    yes: "Yes",
    no: "No",
    actions: "Actions",
    status: "Status",
    name: "Name",
    description: "Description",
    date: "Date",
    amount: "Amount",
    total: "Total",
    subtotal: "Subtotal",
    tax: "Tax",
    discount: "Discount",
    quantity: "Quantity",
    unit: "Unit",
    unitPrice: "Unit Price",
    totalPrice: "Total Price",
    noResults: "No results found",
    retry: "Retry",
    pagination: {
      showing: "Showing {{from}} to {{to}} of {{total}}",
      previous: "Previous",
      next: "Next",
      page: "Page {{page}} of {{totalPages}}",
    },
  },
  shell: {
    nav: {
      dashboard: "Dashboard",
      customers: "Customers",
      orders: "Orders",
      invoices: "Invoices",
      inventory: "Inventory",
      suppliers: "Suppliers",
      procurement: "Procurement",
      crm: "CRM",
      reports: "Reports",
      settings: "Settings",
      logout: "Log out",
    },
  },
} as const;

// =============================================================================
// TYPE-SAFE KEY PATHS
// =============================================================================

export type TranslationKey<
  N extends keyof typeof en,
  Prefix extends string = ''
> = 
  | (typeof en[N] extends object
      ? {
          [K in keyof typeof en[N]]: 
            typeof en[N][K] extends object
              ? TranslationKey<N, `${Prefix}${K & string}.`>
              : `${Prefix}${K & string}`
        }[keyof typeof en[N]]
      : never)
  | `${Prefix}${keyof typeof en[N] & string}`;

// Flatten nested keys for autocomplete
export type FlattenKeys<T, Prefix extends string = ''> = 
  T extends object
    ? { [K in keyof T]: 
        T[K] extends object 
          ? FlattenKeys<T[K], `${Prefix}${K & string}.`> 
          : `${Prefix}${K & string}` 
      }[keyof T]
    : never;

// All possible translation keys
export type AllTranslationKeys = FlattenKeys<typeof en>;

// =============================================================================
// TYPE-SAFE TRANSLATION FUNCTION
// =============================================================================

export interface TypedTFunction {
  <Key extends AllTranslationKeys>(
    key: Key,
    options?: Record<string, unknown>
  ): string;
}

// =============================================================================
// LOCALE FILE MANIFEST (for validation)
// =============================================================================

export interface LocaleFileManifest {
  [namespace: string]: {
    keys: string[];
    lastModified: string;
    hash: string;
  };
}

// =============================================================================
// VALIDATION SCHEMA
// =============================================================================

export interface TranslationValidationRule {
  namespace: string;
  keyPattern: RegExp;
  requiredLocales: string[];
  allowEmpty?: boolean;
  allowHtml?: boolean;
  maxLength?: number;
}

export const VALIDATION_RULES: TranslationValidationRule[] = [
  {
    namespace: 'common',
    keyPattern: /^[a-z]+(\.[a-z]+)*$/,
    requiredLocales: ['en', 'zh-Hant'],
    allowEmpty: false,
    maxLength: 500,
  },
  {
    namespace: 'form',
    keyPattern: /^form\.[a-z]+([A-Z][a-z]+)*$/,
    requiredLocales: ['en', 'zh-Hant'],
    allowEmpty: false,
  },
  {
    namespace: 'error',
    keyPattern: /^errors?\.[a-z]+([A-Z][a-z]+)*$/,
    requiredLocales: ['en', 'zh-Hant'],
    allowEmpty: false,
  },
];

// =============================================================================
// EXPORTS FOR CODE GENERATION
// =============================================================================

export const I18N_SOURCE_LOCALE = 'en';
export const I18N_TARGET_LOCALES = ['zh-Hant'] as const;
export type I18nTargetLocale = typeof I18N_TARGET_LOCALES[number];
